// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJbnpvClu3DvsBomw9w59PMFn98LcbWU',
    appId: '1:263761454148:web:30c6104503dd5ddf7e4811',
    messagingSenderId: '263761454148',
    projectId: 'flutter-shopping-app-dee4f',
    authDomain: 'flutter-shopping-app-dee4f.firebaseapp.com',
    storageBucket: 'flutter-shopping-app-dee4f.firebasestorage.app',
    measurementId: 'G-8H5FVFH566',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6L0gnYSsnlftBWif0IIwxoKD8z07Yyg',
    appId: '1:263761454148:android:a3680724a13b6d167e4811',
    messagingSenderId: '263761454148',
    projectId: 'flutter-shopping-app-dee4f',
    storageBucket: 'flutter-shopping-app-dee4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY3lnzA2up1V8j2kNXYgxy5RVREQCc4LA',
    appId: '1:263761454148:ios:9a8d8975be34bfad7e4811',
    messagingSenderId: '263761454148',
    projectId: 'flutter-shopping-app-dee4f',
    storageBucket: 'flutter-shopping-app-dee4f.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY3lnzA2up1V8j2kNXYgxy5RVREQCc4LA',
    appId: '1:263761454148:ios:9a8d8975be34bfad7e4811',
    messagingSenderId: '263761454148',
    projectId: 'flutter-shopping-app-dee4f',
    storageBucket: 'flutter-shopping-app-dee4f.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJbnpvClu3DvsBomw9w59PMFn98LcbWU',
    appId: '1:263761454148:web:c43e0f559084c0bb7e4811',
    messagingSenderId: '263761454148',
    projectId: 'flutter-shopping-app-dee4f',
    authDomain: 'flutter-shopping-app-dee4f.firebaseapp.com',
    storageBucket: 'flutter-shopping-app-dee4f.firebasestorage.app',
    measurementId: 'G-CJH68EMQ2H',
  );
}
